version: "2"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - PORT=4000
    volumes:
      - ./:/home/node/app
    ports:
      - "4000:4000"
    command: "npm run server"